import { useState } from 'react';
import { TaskItem } from '../types';

export function useTasksMockData() {
  const [tasks, setTasks] = useState<TaskItem[]>([
    {
      id: 'task_001',
      title: 'Review privacy policy',
      description: 'Ensure the privacy policy is up to date and reflects recent processing changes.',
      status: 'in_progress',
      priority: 'high',
      dueDate: '2025-05-20T12:00:00Z',
      createdAt: '2025-05-01T09:00:00Z',
      updatedAt: '2025-05-10T10:00:00Z',
      assignee: 'legal@aura.test',
      resourceType: 'policy',
      resourceId: 'pol_1',
      resourceName: 'Privacy Policy',
    },
    {
      id: 'task_002',
      title: 'Perform DPIA for new tool',
      description: 'Complete DPIA for marketing automation tool rollout.',
      status: 'open',
      priority: 'urgent',
      dueDate: '2025-05-18T12:00:00Z',
      createdAt: '2025-05-05T08:00:00Z',
      updatedAt: '2025-05-08T12:00:00Z',
      assignee: 'dpo@aura.test',
      resourceType: 'dpia',
      resourceId: 'dpia_003',
      resourceName: 'Marketing automation DPIA',
    },
    {
      id: 'task_003',
      title: 'Answer DSR request',
      description: 'Respond to DSR #445 within SLA.',
      status: 'blocked',
      priority: 'medium',
      dueDate: '2025-05-16T12:00:00Z',
      createdAt: '2025-05-06T10:00:00Z',
      updatedAt: '2025-05-10T11:00:00Z',
      assignee: 'support@aura.test',
      resourceType: 'dsr',
      resourceId: 'dsr_445',
      resourceName: 'DSR request #445',
    },
    {
      id: 'task_004',
      title: 'Update TOMs for encryption',
      description: 'Document updated encryption controls for storage systems.',
      status: 'open',
      priority: 'high',
      dueDate: '2025-05-25T12:00:00Z',
      createdAt: '2025-05-07T09:30:00Z',
      updatedAt: '2025-05-07T09:30:00Z',
      assignee: 'security@aura.test',
      resourceType: 'toms',
      resourceId: 'tom_002',
      resourceName: 'Encryption at rest',
    },
    {
      id: 'task_005',
      title: 'Investigate incident #001',
      description: 'Follow up on phishing incident and validate containment.',
      status: 'in_progress',
      priority: 'urgent',
      dueDate: '2025-05-14T12:00:00Z',
      createdAt: '2025-05-08T14:00:00Z',
      updatedAt: '2025-05-09T10:00:00Z',
      assignee: 'security@aura.test',
      resourceType: 'incident',
      resourceId: 'inc_001',
      resourceName: 'Phishing attack reported',
    },
    {
      id: 'task_006',
      title: 'Add new ROPA record',
      description: 'Document processing activities for customer analytics.',
      status: 'completed',
      priority: 'medium',
      dueDate: '2025-05-05T12:00:00Z',
      createdAt: '2025-04-28T09:00:00Z',
      updatedAt: '2025-05-04T15:00:00Z',
      assignee: 'owner@aura.test',
      resourceType: 'ropa',
      resourceId: 'ropa_003',
      resourceName: 'Customer analytics processing',
    },
  ]);

  return { tasks, setTasks, isLoading: false, isError: false };
}

export default useTasksMockData;
